const medicineNames = [
  'Betaloc Zok',
  'Concor',
  'Paracetamol Sol Perf',
  'Rigevidon',
  'Rispolept',
  'Seroxat',
  'Synjardy',
  'Adrenalina Terapia',
  'Adrenostazin',
  'Driptane',
  'Etamsilat Zentiva',
  'Orfiril Long',
  'Romparkin',
  'Simvacard',
  'Zenra',
  'Canzeno',
  'Fluconazole',
  'Quetiapina Teva',
  'Camilia',
  'Cystone',
  'Digenzym Plus',
  'Dulcolax',
  'Liv 52',
  'Magcombo',
  'Olynth Ha',
  'Protectis Picaturi Pentru Copii',
  'Secom Hydraplenish Plus Msm',
  'Strepsils Intensiv Miere Si Lamaie',
  'Tussodep Sirop',
  'Paracetamol',
  'Ibuprofen',
  'Amoxicilina',
  'Ciprofloxacin',
  'Diclofenac',
  'Metformin',
  'Omeprazol',
  'Simvastatin',
  'Nurofen',
  'Debridat',
];

module.exports = { medicineNames };
